---
- hosts: localhost
  become: yes

  roles:
    - geerlingguy.docker

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600


  #handlers:
  #  - name: restart apache
  #    service: name=apache2 state=restarted

  tasks:
    - name: Install packages
      apt:
        name:
          # req for NAS connection
          - nfs-common
          - steam
          - atom
          - vim
          # req for CAC authentication (DoD websites)
          - opensc
          - obs-studio
          - zsh
          #- discord
          #- spotify-client
        state: present

    #- name: Install flatpaks
       #flatpak: name={{ item }} state=present
       #loop: [discord, spotify]
