---
- hosts: localhost
  become: yes

  roles:
    - geerlingguy.docker

  pre_tasks:

    #- name: Add GitHub CLI Apt-Key
      #apt_key:
        #keyserver: keyserver.ubuntu.com
        #id: C99B11DEB97541F0

    - name: Add Apt-Keys
      apt_key:
        keyserver: "{{ item.key }}"
        id: "{{ item.value }}"
      loop: "{{ tag_data | dict2items }}"
      vars:
        tag_data:
          keyserver.ubuntu.com: C99B11DEB97541F0
          # example.keyserver: key.id

    - name: Add Apt-Keys from URL
      apt_key:
        url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
        state: present

    - name: Add Apt-Repositories
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        - deb-src https://cli.github.com/packages focal main
        - deb http://repository.spotify.com stable non-free

    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600


  #handlers:
  #  - name: restart apache
  #    service: name=apache2 state=restarted

  tasks:
    - name: Install packages
      apt:
        name:
          # req for NAS connection
          - nfs-common
          - steam
          - atom
          - vim
          # req for CAC authentication (DoD websites)
          - opensc
          - obs-studio
          - zsh
          - discord
          #- spotify-client
          - gh
          - git
          - python3-pip
          - python3
        state: present

    #- name: Install flatpaks
       #flatpak: name={{ item }} state=present
       #loop: [discord, spotify]

    - name: Set up git name
      community.general.git_config:
        name: user.name
        value: "imkumpy"
        scope: global

    - name: Set up git email
      community.general.git_config:
        name: user.email
        value: "lebergarrett@gmail.com"
        scope: global

    - name: check if awscli exists
      stat:
        path: /home/kump/Downloads/aws
      register: awscli_dir

    - name: Download awscli zip
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /home/kump/Downloads/awscliv2.zip
      when: awscli_dir.stat.exists == False

    - name: Unzip awscli zip
      unarchive:
        src: /home/kump/Downloads/awscliv2.zip
        dest: /home/kump/Downloads/
        remote_src: yes
        creates: /home/kump/Downloads/aws

    - name: Run awscli install script
      command: ./aws/install
      args:
        chdir: /home/kump/Downloads
        creates: /usr/local/bin/aws
