---
- hosts: localhost
  become: yes

  roles:
    #- geerlingguy.docker

  pre_tasks:

    #- name: Add GitHub CLI Apt-Key
      #apt_key:
        #keyserver: keyserver.ubuntu.com
        #id: C99B11DEB97541F0

    - name: Add Apt-Keys
      apt_key:
        keyserver: "{{ item.key }}"
        id: "{{ item.value }}"
      loop: "{{ tag_data | dict2items }}"
      vars:
        tag_data:
          # Github CLI
          keyserver.ubuntu.com: C99B11DEB97541F0
          # example.keyserver: key.id

    - name: Add Apt-Keys from URL
      apt_key:
        # Spotify client
        url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
        state: present

    - name: Add Apt-Repositories
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        # Github CLI
        - deb-src https://cli.github.com/packages focal main
        # Spotify Client
        - deb http://repository.spotify.com stable non-free

    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600


  #handlers:
  #  - name: restart apache
  #    service: name=apache2 state=restarted

  tasks:
    - name: Install packages
      apt:
        name:
          # req for NAS connection
          - nfs-common
            #- steam
            #- atom
          - vim
          # req for CAC authentication (DoD websites)
          #- opensc
          #- obs-studio
          - zsh
            #- discord
          #- spotify-client
          #- gh
          - git
          - python3-pip
          - python3
          - unzip
        state: present

    #- name: Install flatpaks
       #flatpak: name={{ item }} state=present
       #loop: [discord, spotify]

    - name: Set up git username
      community.general.git_config:
        name: user.name
        value: "imkumpy"
        scope: global

    - name: Set up git email
      community.general.git_config:
        name: user.email
        value: "lebergarrett@gmail.com"
        scope: global

    - name: Ensure downloads dir exists
      file:
        path: /home/kump/Downloads
        state: directory

    - name: Check if awscli exists
      stat:
        path: /usr/local/bin/aws
        #path: /home/kump/Downloads/aws
      register: awscli_dir

    - name: Download awscli zip
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /home/kump/Downloads/awscliv2.zip
      when: awscli_dir.stat.exists == False

    - name: Unzip awscli zip
      unarchive:
        src: /home/kump/Downloads/awscliv2.zip
        dest: /home/kump/Downloads/
        remote_src: yes
        creates: /usr/local/bin/aws
        #creates: /home/kump/Downloads/aws

    - name: Run awscli install script
      command: ./aws/install
      args:
        chdir: /home/kump/Downloads
        creates: /usr/local/bin/aws

    - name: Check if Oh My Zsh! exists
      stat:
        path: /home/kump/.oh-my-zsh
      register: ohmyzsh_dir

    - name: Download Oh My Zsh! install script
      get_url:
        url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /home/kump/Downloads/ohmyzsh-install.sh
      when: ohmyzsh_dir.stat.exists == False

    - name: Make install script executable
      file:
        path: /home/kump/Downloads/ohmyzsh-install.sh
        mode: 0744 

    - name: Run Oh My Zsh! install script
      command: ./ohmyzsh-install.sh
      args:
        chdir: /home/kump/Downloads
        creates: /home/kump/.oh-my-zsh

    - name: Create mount pount for shared drive
      file:
        path: /media/shared
        state: directory

    - name: Mount /media/shared drive
      mount:
        path: /media/shared
        src: 192.168.1.114:mnt/Shared/ShareDataSet
        fstype: nfs
        opts: defaults
        state: present



        #TODO
        #Adjust downloads folder, awscli, shared drive and ohmyzsh installer permissions to match kump user instead of being root
