# Run commands below to install roles/collections listed in this file
# ansible-galaxy role install -r requirements.yml
# ansible-galaxy collection install -r requirements.yml

roles:
  # This role installs docker and docker-compose
  - geerlingguy.docker
  # This role installs and configures golang
  - fubarhouse.golang

collections:
  - community.general
